spring.application.name=provabackend
api.security.token.secret=meuSegredoSuperSeguro123
spring.datasource.url=jdbc:mysql://localhost:3306/prova_fullstack
spring.datasource.username=root
spring.datasource.password=maosinho
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

